environment: dev

services:
  auth:
    base_url: http://localhost:3000
    # az auth szolgáltatás adja ki a tokent, de itt már megvan előre (pl. kézzel vagy login után)
    jwt_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.xample

  user:
    base_url: http://localhost:3000